spring:
  application:
    name: zuul-gateway

server:
  port: 5555

zuul:
  routes:
    eureka-client:
      path: /eureka-client/**
      serveiceId: eureka-client
#    user-service:
#      /user-service/**

  ignored-patterns:
    /user-service/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
