spring:
  application:
    name: user-service
server:
  port: 2101
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
info:
  profile: dev
  author: szg
  city: beijing