spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:3001/
      profile: default
      label: master
  server:
  port: 2101
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/