spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:canfeng/spring-cloud-demos.git
          searchPaths: config-repo
server:
  port: 3001

security:
  user:
    name: config-admin
    password: config-admin



